from __future__ import absolute_import
from __future__ import print_function
from __future__ import division
from mwptoolkit.module.Attention import group_attention,multi_head_attention,self_attention,seq_attention,tree_attention