from __future__ import absolute_import
from __future__ import print_function
from __future__ import division
from mwptoolkit.loss import abstract_loss,binary_cross_entropy_loss,cross_entropy_loss,masked_cross_entropy_loss,mse_loss,nll_loss,smoothed_cross_entropy_loss