from __future__ import absolute_import
from __future__ import print_function
from __future__ import division

from mwptoolkit.utils.preprocess_tool import dataset_operator,equation_operator,number_operator,number_transfer,sentence_operator